@host = http://localhost:3000

GET {{host}}

###

GET {{host}}/users

###

POST {{host}}/users
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "testpassword",
  "name": "test"
}

###

DELETE {{host}}/users/5f13c6ec9cdf4030c071252c